### ISSUE TITLE
Msata not working

### ISSUE THREAD

**Issue by kjarex** [SpookySkeletons/Coreboot_8770w#5]
At least not for me. Is it working for anyone else?
I guess it would need another port registered in the device tree. Which port could be probably figured out via the efi parts of official firmware - but I would have no clue how to do that (I would be likely faster just by trying them randomly, but I would want to avoid to do that either).

**Comment by SpookySkeletons** [comment]
Msata works as of this commit. The change allows the mpcie port to be used as a data port. 2a2d0d880ddd18e9809b6ea1aed4d4baa88bd272

Add this change to your master coreboot tree and it will pop right up

**Comment by kjarex** [comment]
I'm not sure if my problem might not be a different one (I have absolute no UEFI experience, so there is a high chance I do there something wrong). My build used already the newer value for the sata port. But `devices` in the UEFI shell doesn't list my msata (while I would expect it to be listed there as well - would this be correct?). So I assumed that msata support would be just missing.
